apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-nzjyngtz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nexus-docker-nexus.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/backend-tests-go-nzjyngtz:a574641c8d03466e381c33a62911cfe5d4999ab1@sha256:04be58804154f958685145385325f452c9d6180821a2440f40d20bed2b980f6c
          name: container-image
